### ISSUE TITLE
Cannot reproduce the result in the paper

### ISSUE THREAD

**Issue by lchenat** [jacobandreas/craft#1]
Hi, I tried to run your code on my laptop and it works fine. The problem is that I cannot reproduce the result on light-joint-feat-plan task. I changed the experiment name to "test" in comfig.yaml ran the main.py directly. The final result is around 0.3. Are there any parameters that I need to change in order to reproduce the result?

**Comment by jacobandreas** [comment]
which experiment are you trying to reproduce?

**Comment by lchenat** [comment]
The light_joint-feat-plan experiment. I only changed the "name" field in config.yaml and ran then ran main.py

**Comment by jacobandreas** [comment]
That particular evaluation condition doesn't correspond to any experiment in the paper. If you leave it set to `train`, you should get the "Joint" line in figure 4b. Is that what you want?

**Comment by jacobandreas** [comment]
Oh sorry misunderstood---changing the "name" field shouldn't make a difference. Not sure why your number is lower but I'll re-run locally when I get a chance.

**Comment by jacobandreas** [comment]
Oh here's a possible source of confusion: because my code is gross, the `[reward]` line in the log doesn't actually correspond to the value that shows up in the plot. In particular `[reward]` is just the average reward obtained for all tasks in the current batch, where the probability of choosing those tasks is weighted according to the curriculum (which will assign higher weight to tasks where we're doing badly). What you actually want is to take the second number on every `[task]` line, add them together, and divide by the _total_ number of tasks for the given environment.

If you'd like, I can send you the code used to generate the plots in the paper.

**Comment by jacobandreas** [comment]
Following up: I re-ran the config in the branch `exp/light_joint-feat-plan` on an ec2 c4.2xlarge, and it reproduced exactly. I also tried a clean checkout of master using a different seed on my local GPU box; the training curve was a little different but it looks like the final result is going to be basically the same (currently at ~41% success on step 2.7m; number in the paper is ~42%).

This baseline does seem a little more sensitive to initialization, and I'm in the process of generating new versions of the plots that will show variation across runs explicitly---it's possible that's all you're seeing, though I haven't seen any drops nearly as big as what you're reporting. 

Let me know if there's anything else I can do to help.

**Comment by jacobandreas** [comment]
Following up again---just found a run where learning never got off the ground at all, so it's certainly possible. Should still be possible to reproduce our results exactly, but you might just try a different random seed.

**Comment by lchenat** [comment]
Here is how I ran the experiment: I changed the "name" field in config.yaml from "light_joint-feat-plan" to "light_joint-feat-plan-test" and ran main.py. Then I compare my run.log to the one already existed in exp/light_joint-feat-plan. Here is the last block of INFO in my run.log:

2017-08-14 19:13:27,693 INFO     [max steps] 2
2017-08-14 19:22:51,403 INFO     [step] 3042800
2017-08-14 19:22:51,403 INFO     [task] go[LL] 0.0488785468809 0.921987271607
2017-08-14 19:22:51,403 INFO     [task] go[LD] 0.0767539557438 0.877969622225
2017-08-14 19:22:51,403 INFO     [task] go[UL] 0.0629929496834 0.90712945591
2017-08-14 19:22:51,403 INFO     [task] go[RD] 0.622727890168 0.0
2017-08-14 19:22:51,403 INFO     [task] go[UR] 0.188646657524 0.708639065931
2017-08-14 19:22:51,403 INFO
2017-08-14 19:22:51,403 INFO     [rollout0] [3, 0, 4, 2, 0, 0, 0, 3, 0, 3, 4, 2, 2, 0, 6, 2, 2, 2, 0, 0, 2, 5]
2017-08-14 19:22:51,403 INFO     [rollout1] [4, 4, 1, 0, 4, 5, 1, 5]
2017-08-14 19:22:51,403 INFO     [rollout2] [1, 0, 1, 0, 3, 1, 3, 1, 4, 5, 3, 4, 5]
2017-08-14 19:22:51,404 INFO     [reward] 0.30287
2017-08-14 19:22:51,404 INFO     [error] [ -1.00853289e-05   4.33201401e-05]
2017-08-14 19:22:51,404 INFO
2017-08-14 19:22:51,404 INFO     [min reward] 0.0
2017-08-14 19:22:51,404 INFO

The weird thing here is that the the score for task go[RD] is always 0 in all INFOs. I think that's why I got a low reward compared to the one in your original running log in exp/light_joint-feat-plan. I tried this on both my laptop and server and the result is the same (score for go[RD] is always 0). I am not sure what happen. Did you run main.py directly without modifying any parameters in the original code on github?

**Comment by jacobandreas** [comment]
I also changed the name. The scenario where it fails to get started at all on some tasks seem to happen with some random initializations, so it could just be a numerical difference between your hardware and mine. I was able to reproduce exactly on ec2; if you don't want to deal with setting that up you can also try a few different values for the seed in `models/modular_ac.py`

**Comment by tongzhoumu** [comment]
Hello, I met the exactly same problem. I tried different random seeds, but it doesn't seem work. Do you solve the problem at last? @lchenat @jacobandreas

**Comment by lchenat** [comment]
No... I tried several random seeds but the highest I can get is 0.45.

**Comment by jacobandreas** [comment]
The number you were trying to reproduce was the 0.42, right? Numbers may not be exactly the same depending on what hardware you're running on.

This experiments directory in this branch:
https://github.com/jacobandreas/psketch/tree/exp/light_joint-feat-plan/experiments
contains runs across multiple seeds for this particular experiment. Scores are .42 and .54 on successful runs; it fails on the others.
