### ISSUE TITLE
Question on algorithms used to build baseline

### ISSUE THREAD

**Issue by lchenat** [jacobandreas/craft#2]
May I ask what algorithm did you use when you train the joint policy and independent policies? ('Joint' and 'Indep' in Figure 4 in your paper) Moreover, what algorithms are implemented in models 'attentive.py' and 'reflex.py'?

**Comment by jacobandreas** [comment]
As we discussed before, the configurations used for these experiments can be obtained by checking out the relevant branches under `exp/`. The other models are not used in this paper.
