### ISSUE TITLE
Question on adaptation & zero-shot

### ISSUE THREAD

**Issue by NTUwanderer** [jacobandreas/craft#3]
May I ask which part of the source code shows the results of adaptation (learn the form of a suitable sketch) and zero-shot? All I see is just the training process.
Thanks for the response!

**Comment by jacobandreas** [comment]
Never got around to merging these back into master---look at the `exp/craft_holdout` and `exp/craft_transfer` branches.

**Comment by NTUwanderer** [comment]
I'm not sure if I think it right or not: Does the adaptation (in exp/craft_transfer) apply all subtasks learned before in a row and see if the new task is accomplished, if not, do the subtasks in the same order again?
Thanks for your patience!

**Comment by jacobandreas** [comment]
As described in the paper, we do ordinary Q learning to learn a policy over
subtasks. This is implemented in modular_ac_interactive.
