### ISSUE TITLE
How to visualize the crafting environment world in figure 3a?

### ISSUE THREAD

**Issue by zhan0903** [jacobandreas/craft#4]
I'd like to see the agent acting in the crafting world(in a GUI way), how to make it? Thanks.

**Comment by jacobandreas** [comment]
check out CraftWorld.visualize---it's not baked into any of the training scripts but it will give you a little curses animation. The figures in the paper were made in Keynote :)

**Comment by zhan0903** [comment]
Thank you.

Han Zheng
z.han0903@gmail.com
