### ISSUE TITLE
no gpu needed when running experiment?

### ISSUE THREAD

**Issue by Wongcheukwai** [jacobandreas/craft#8]
hi Jacob,

i was running your experiment light_modular and i found my gpu-utli(nividia-smi) is always zero. Does the same situation happen to you? Or is it true that your algorithm doesn't have gpu part(just cpu)? sorry this question may sound a little bit stupid.

**Comment by jacobandreas** [comment]
Not stupid at all---i didn't have access to a gpu when I ran the initial
experiments so it's all cpu. Should be very straightforward to port.

**Comment by Wongcheukwai** [comment]
but porting, do you mean uploading the model(modular_ac) and the data to the gpu? however, since i am new, i don't know what data in reinforcement learning should be uploaded to gpu. Any hint?
Thnx

**Comment by jacobandreas** [comment]
If you move the model to the GPU, then any data you feed it also needs to
be sent to the GPU. There should be standard TF tutorials on how to do this.
